/* Shared NPC poses, including seated drivers and conversational gestures.
   The playable character is never instantiated here. */
window.QuarterNPCActors=class QuarterNPCActors {
 constructor(crowd){this.crowd=crowd;this.B=crowd.B;this.seats=[];this.carSeats=new Map();this.talks=[];this.extractions=[];this.speechClock=0;
  for(let variant=0;variant<crowd.models.length;variant++){
   const seat=this.pool(variant,'seat');this.seated(seat);this.seats.push(seat);
   this.talks.push(this.pool(variant,'talk-0'),this.pool(variant,'talk-1'));
   this.extractions.push(this.pool(variant,'extraction'));
  }
 }
 pool(variant,label){const c=this.crowd,m=c.models[variant],base=m.idles[0],factory=Object.create(c);Object.assign(factory,{container:m.container,pack:base.pack,clips:base.clips});
  const p=factory.makeNPCPool('npc-'+variant+'-'+label,'idle',0);Object.assign(p,{scale:base.scale,center:base.center,facing:base.facing,variant,pack:base.pack,clips:base.clips});c.poseNPC(p,0);p.groundLow=p.low;p.phase=label.endsWith('1')?.5:0;
  const rotation=this.B.Matrix.RotationY(-p.facing);p.axes={};for(const [name,node] of Object.entries(p.nodes)){const world=node.computeWorldMatrix(true),inverse=this.B.Matrix.Invert(world),sign=world.determinant()<0?-1:1;p.axes[name]=[this.B.Axis.X,this.B.Axis.Y,this.B.Axis.Z].map(axis=>this.B.Vector3.TransformNormal(this.B.Vector3.TransformNormal(axis,rotation),inverse).normalize().scale(sign));}return p;
 }
 rotate(p,name,pitch=0,yaw=0,roll=0){const node=p.nodes[name],axes=p.axes[name];if(!node||!axes)return;for(const [i,angle] of [pitch,yaw,roll].entries())if(angle)node.rotationQuaternion=node.rotationQuaternion.multiply(this.B.Quaternion.RotationAxis(axes[i],angle));}
 prepare(p){for(const j of p.joints)j.node.computeWorldMatrix(true);p.skeleton.prepare(true);p.low=this.crowd.lowestNPCSole(p);}
 seated(p,knee=1.4){this.crowd.poseNPC(p,0);this.rotate(p,'Spine',.18);for(const side of ['Left','Right']){this.rotate(p,side+'UpLeg',-1.35);this.rotate(p,side+'Leg',knee);this.rotate(p,side+'Foot',-.08);this.rotate(p,side+'Arm',-.85,0,side==='Left'?-.05:.05);this.rotate(p,side+'ForeArm',-.65);}this.prepare(p);p.seatRotations=p.joints.map(j=>j.node.rotationQuaternion.clone());}
 instance(p,name){const mesh=p.mesh.createInstance(name);QuarterClothing.tint(this.B,mesh,Array.from(name).reduce((n,c)=>n+c.charCodeAt(0),0));mesh.parent=null;mesh.rotationQuaternion=this.B.Quaternion.Identity();mesh.isPickable=false;mesh.receiveShadows=true;return mesh;}
 draw(mesh,p,x,y,z,heading,scale=1,grounded=true){const B=this.B,size=p.scale*scale,yaw=heading+p.facing,c=Math.cos(yaw),s=Math.sin(yaw),matrix=B.Matrix.Compose(new B.Vector3(size,size,size),B.Quaternion.RotationYawPitchRoll(yaw,0,0),new B.Vector3(x-size*(p.center.x*c+p.center.z*s),y-(grounded?p.low:p.groundLow)*size,z-size*(-p.center.x*s+p.center.z*c)));p.world.multiply(matrix).decompose(mesh.scaling,mesh.rotationQuaternion,mesh.position);}
 seat(root,variant=0){let pool=this.seats[variant];if(root.driver.feet){const key=variant+'/'+root.driver.profile;if(!this.carSeats.has(key)){const p=this.pool(variant,'car-seat-'+root.driver.profile);this.seated(p,root.driver.knee);const B=this.B,normalizer=B.Matrix.RotationY(p.facing).multiply(B.Matrix.Scaling(p.scale,p.scale,p.scale)),inverse=B.Matrix.Invert(normalizer),hip=B.Vector3.TransformCoordinates(p.nodes.Hips.getAbsolutePosition(),normalizer);for(const [i,side] of ['Left','Right'].entries()){const foot=root.driver.feet[i],target=hip.add(new B.Vector3(foot[0]-root.driver.hip[0],foot[1]-root.driver.hip[1],foot[2]-root.driver.hip[2]));QuarterSeatedLegs.solve(B,p.nodes,side,B.Vector3.TransformCoordinates(target,inverse));}this.prepare(p);p.seatRotations=p.joints.map(j=>j.node.rotationQuaternion.clone());this.carSeats.set(key,p);}pool=this.carSeats.get(key);}const mesh=this.instance(pool,'npc-driver-'+root.name);return {root,pool,mesh,variant,occupied:true};}
 placeSeat(actor,root=actor.root){const p=root.driver.position,B=this.B,point=B.Vector3.TransformCoordinates(new B.Vector3(...p),root.computeWorldMatrix(true));this.draw(actor.mesh,actor.pool,point.x,point.y,point.z,root.rotation.y,1,false);const desired=B.Vector3.TransformCoordinates(new B.Vector3(...root.driver.hip),root.getWorldMatrix()),hip=B.Vector3.TransformCoordinates(actor.pool.nodes.Hips.getAbsolutePosition(),B.Matrix.Invert(actor.pool.world).multiply(actor.mesh.computeWorldMatrix(true)));actor.seatOffset=desired.subtract(hip);actor.mesh.position.addInPlace(actor.seatOffset);actor.mesh.setEnabled(actor.occupied&&root.isEnabled());}
 update(dt){this.speechClock+=dt;if(this.speechClock<1/30)return;this.speechClock=0;
  for(const p of this.talks){if(!p.count)continue;const time=this.crowd.time+p.variant*.63+p.phase;this.crowd.poseNPC(p,time/p.clips.idle.duration);const gesture=.5+.5*Math.sin(time*2.4);this.rotate(p,'Head',.025*Math.sin(time*3),.08*Math.sin(time*1.5));this.rotate(p,'RightArm',-.30-.25*gesture,0,.08);this.rotate(p,'RightForeArm',-.5-.28*gesture);this.rotate(p,'LeftForeArm',-.18-.15*Math.sin(time*1.8));this.prepare(p);}
 }
 extraction(actor,progress){const p=this.extractions[actor.variant],seat=actor.pool;this.crowd.poseNPC(p,0);const blend=Math.max(0,Math.min(1,progress));p.joints.forEach((j,i)=>this.B.Quaternion.SlerpToRef(seat.seatRotations[i],j.node.rotationQuaternion,blend,j.node.rotationQuaternion));this.rotate(p,'Spine',-.22*Math.sin(Math.PI*blend));this.rotate(p,'RightArm',-.25);this.prepare(p);return p;}
 snapshot(){return {sources:this.seats.map(p=>this.crowd.models[p.variant].source),playerClones:0,seatedPalettes:this.seats.length,carSeatedPalettes:this.carSeats.size,talkingPalettes:this.talks.length,extractionPalettes:this.extractions.length};}
};
