/* Original Hindi reactions, predecoded offline; one voice at a time, with cooldowns. */
window.QuarterNPCSpeech=class QuarterNPCSpeech {
 static async create(){const speech=new this();await QuarterAssets.load('assets/npc-voices-data.js');speech.clips=await Promise.all(QUARTER_NPC_VOICES.map(async c=>{const bytes=Uint8Array.from(atob(c.src.split(',')[1]),v=>v.charCodeAt(0));return {...c,buffer:await speech.context.decodeAudioData(bytes.buffer)};}));return speech;}
 constructor(){this.context=new (window.AudioContext||window.webkitAudioContext)();this.last=-100;this.count=0;this.sequence=0;this.active=null;this.cooldowns=new Map();document.addEventListener('visibilitychange',()=>{if(document.hidden)this.active?.stop();});document.getElementById('sound').addEventListener('click',()=>{if(!QUARTER_AUDIO.snapshot().enabled)this.active?.stop();});}
 unlock(){return this.context.resume();}
 play(agent,event='bump',distance=0){const now=performance.now()/1000;if(!window.STREET?.started||document.hidden||!QUARTER_AUDIO.snapshot().enabled||now-this.last<2.8||now-(this.cooldowns.get(agent.id)??-100)<10)return false;
  const gender=[2,4,5].includes(agent.variant)?'female':'male',choices=this.clips.filter(c=>c.gender===gender&&c.event===event),clip=choices[this.sequence++%choices.length];if(!clip)return false;
  this.active?.stop();const source=this.context.createBufferSource(),gain=this.context.createGain(),pan=this.context.createStereoPanner();source.buffer=clip.buffer;gain.gain.value=Math.max(.04,.28-distance*.045);this.lastGain=gain.gain.value;const player=STREET.player,dx=(agent.x??player.position.x)-player.position.x,dz=(agent.z??player.position.z)-player.position.z;pan.pan.value=Math.max(-.8,Math.min(.8,(dx*Math.cos(player.heading)-dz*Math.sin(player.heading))/6));source.connect(gain).connect(pan).connect(this.context.destination);this.active=source;QUARTER_AUDIO.duckVoice=true;QUARTER_AUDIO.mix();source.onended=()=>{if(this.active===source){this.active=null;QUARTER_AUDIO.duckVoice=false;QUARTER_AUDIO.mix();}};source.start();this.last=now;this.count++;this.lastClip=clip.key;this.cooldowns.set(agent.id,now);if(this.cooldowns.size>256)this.cooldowns.clear();return true;
 }
 snapshot(){return {language:'Hindi (India)',source:'Original synthesized dialogue',clips:this.clips?.length||0,played:this.count,lastClip:this.lastClip,gain:this.lastGain??.28,context:this.context.state,simultaneous:1};}
};
