/* Vehicle ownership, NPC extraction and enter/exit transitions.
   Pooled NPC assets and authored rig transitions; no copied GTA animations. */
window.QuarterVehicleActions=class QuarterVehicleActions {
 constructor(ctx){Object.assign(this,ctx);this.records=[];this.active=null;this.history=[];this.evicted=[];this.victims=[];
  this.records.push({id:'primary',name:'rickshaw',root:this.primary,wheels:this.primaryWheels,occupied:false,kind:'rickshaw'});
  for(const a of this.traffic.agents)this.records.push({id:'traffic-'+a.id,name:a.name||'rickshaw',root:a.root,wheels:a.wheels,door:a.door,parts:a.vehicleParts,occupied:true,occupant:a.occupant,agent:a,kind:a.kind});
  for(const [i,v] of this.parked.vehicles.entries()){v.contact.unfreezeWorldMatrix();v.contact.parent=v.root;v.contact.position.set(0,.004,0);const parts=QuarterVehicleParts(this.B,v),occupant=this.crowd.actors.seat(v.root,i%this.crowd.models.length);this.records.push({id:v.name,name:v.name.replaceAll('-',' '),root:v.root,wheels:parts.wheels,door:parts.door,parts,occupied:true,occupant,parked:v,kind:'car'});this.crowd.actors.placeSeat(occupant);}
  for(let variant=0;variant<this.crowd.models.length;variant++){this.victims.push(this.crowd.actors.instance(this.crowd.actors.extractions[variant],'extracted-npc-'+variant));this.victims[variant].setEnabled(false);for(let k=0;k<2;k++){const mesh=this.crowd.actors.instance(this.crowd.pools[variant*4+k],'evicted-walker-'+variant+'-'+k);mesh.setEnabled(false);const idle=this.crowd.actors.instance(this.crowd.idlePools[variant*2+k],'evicted-idle-'+variant+'-'+k);idle.setEnabled(false);this.evicted.push({variant,mesh,idle,visible:false,time:0});}}
 }
 cancel(){const a=this.active;if(a){if(a.record.door)a.record.door.rotation.y=0;if(a.record.agent)a.record.agent.held=false;if(a.occupied&&!a.evicted&&!a.record.occupant.occupied){this.releaseVictim(a.record.occupant,this.player.position,a.record.root.rotation.y);a.evicted=true;}}for(const m of this.victims)m.setEnabled(false);for(const r of this.records)if(r.agent)r.agent.controlled=false;this.active=null;this.crowd.player.action=null;}
 shape(record){return record.root.collision;}
 worldPoint(r,x,y,z){return this.B.Vector3.TransformCoordinates(new this.B.Vector3(x,y,z),r.root.computeWorldMatrix(true));}
 doorPoint(r,player=this.player.position){const local=this.B.Vector3.TransformCoordinates(player,this.B.Matrix.Invert(r.root.computeWorldMatrix(true))),side=r.kind==='car'?1:local.x<0?-1:1;return {side,point:this.worldPoint(r,side*(this.shape(r).halfWidth+.65),this.world.heightAt(r.root.position.x+side*1.6,r.root.position.z),r.root.driver.position[2])};}
 nearest(position=this.player.position){let best=null,distance=Infinity;for(const r of this.records){if(!r.root.isEnabled())continue;const door=this.doorPoint(r,position),d=r.kind==='rickshaw'?Math.hypot(position.x-r.root.position.x,position.z-r.root.position.z):this.B.Vector3.Distance(position,door.point);if(d<(r.kind==='rickshaw'?3.6:2.2)&&d<distance){best=r;distance=d;}}return best;}
 pointBlocked(x,z,ignore=null){return this.records.some(r=>{if(r.root===ignore)return false;const h=r.root.rotation.y,dx=x-r.root.position.x,dz=z-r.root.position.z,lx=dx*Math.cos(h)-dz*Math.sin(h),lz=dx*Math.sin(h)+dz*Math.cos(h),s=this.shape(r);return Math.abs(lx)<s.halfWidth+.17&&lz>s.minZ-.17&&lz<s.maxZ+.17;});}
 carBlocked(x,z,h,shape,ignoreRoot,ignoreTraffic=false){return this.carPenetration(x,z,h,shape,ignoreRoot,ignoreTraffic)>0;}
 carPenetration(x,z,h,shape,ignoreRoot,ignoreTraffic=false){const centerZ=(shape.minZ+shape.maxZ)/2,px=x+Math.sin(h)*centerZ,pz=z+Math.cos(h)*centerZ,halfLength=(shape.maxZ-shape.minZ)/2;
  return this.records.reduce((total,r)=>{if(r.root===ignoreRoot||!r.root.isEnabled()||ignoreTraffic&&r.agent)return total;const s=this.shape(r),rh=r.root.rotation.y,rz=(s.minZ+s.maxZ)/2,dx=r.root.position.x+Math.sin(rh)*rz-px,dz=r.root.position.z+Math.cos(rh)*rz-pz,otherLength=(s.maxZ-s.minZ)/2;
   const depths=[[Math.cos(h),-Math.sin(h)],[Math.sin(h),Math.cos(h)],[Math.cos(rh),-Math.sin(rh)],[Math.sin(rh),Math.cos(rh)]].map(([ax,az])=>Math.abs(ax*Math.cos(h)-az*Math.sin(h))*shape.halfWidth+Math.abs(ax*Math.sin(h)+az*Math.cos(h))*halfLength+Math.abs(ax*Math.cos(rh)-az*Math.sin(rh))*s.halfWidth+Math.abs(ax*Math.sin(rh)+az*Math.cos(rh))*otherLength+.025-Math.abs(dx*ax+dz*az));return total+Math.max(0,Math.min(...depths));
  },0);
 }
 begin(record){if(this.active||!record)return false;const d=this.doorPoint(record),occupied=record.occupant?.occupied??false;this.active={record,kind:'enter',time:0,occupied,side:d.side,start:this.player.position.clone(),startHeading:this.player.heading,stage:'approach'};if(record.agent){record.agent.held=true;for(const [key,id] of this.traffic.locks)if(id===record.agent.id)this.traffic.locks.delete(key);}this.player.speed=0;this.crowd.player.resetMotion();this.crowd.player.cacheSeat(record.root);this.status(occupied?'Pulling out the driver…':'Entering '+record.name+'…');return true;}
 exit(record){if(this.active)return false;const s=this.shape(record),spots=[[s.halfWidth+.7,record.root.driver.position[2]],[-s.halfWidth-.7,record.root.driver.position[2]],[0,s.minZ-.8]],spot=spots.map(([x,z])=>this.worldPoint(record,x,0,z)).find(p=>this.footAllowed(p.x,p.z));if(!spot){this.status('Wait for a clear space to get out');return false;}spot.y=this.world.heightAt(spot.x,spot.z);const seat=this.worldPoint(record,...record.root.driver.position);this.active={record,kind:'exit',time:0,start:seat,end:spot,side:1,stage:'exit'};this.onFoot(seat,record.root.rotation.y);return true;}
 smooth(t){t=Math.max(0,Math.min(1,t));return t*t*(3-2*t);}
 lerp(a,b,t){return this.B.Vector3.Lerp(a,b,this.smooth(t));}
 update(dt){for(const r of this.records)if(r.occupant?.occupied&&!r.agent)this.crowd.actors.placeSeat(r.occupant);
  for(const e of this.evicted)if(e.visible){e.time+=dt;const dx=e.goal.x-e.position.x,dz=e.goal.z-e.position.z,d=Math.hypot(dx,dz);if(d>.08){const step=Math.min(d,dt*1.5);const x=e.position.x+dx/d*step,z=e.position.z+dz/d*step;if(!this.crowd.agents.some(a=>Math.hypot(x-a.x,z-a.z)<.66)){e.position.x=x;e.position.z=z;}else{e.goal=e.position.clone();}e.heading=Math.atan2(dx,dz);}const moving=Math.hypot(e.goal.x-e.position.x,e.goal.z-e.position.z)>.08,p=moving?this.crowd.pools[e.variant*4]:this.crowd.idlePools[e.variant*2];e.mesh.setEnabled(moving);e.idle.setEnabled(!moving);this.crowd.actors.draw(moving?e.mesh:e.idle,p,e.position.x,this.world.heightAt(e.position.x,e.position.z),e.position.z,e.heading);if(e.time>35||Math.hypot(e.position.x-this.player.position.x,e.position.z-this.player.position.z)>95){e.mesh.setEnabled(false);e.idle.setEnabled(false);e.visible=false;}}
  const a=this.active;if(!a)return;const r=a.record,actor=this.crowd.player,door=this.doorPoint(r),seat=this.worldPoint(r,...r.root.driver.position);
  if(r.agent&&r.agent.speed>.12)return;a.time+=dt;const t=a.time;
  if(a.kind==='exit'){const p=this.smooth(t/1.25);this.player.position.copyFrom(this.B.Vector3.Lerp(a.start,a.end,p));this.player.heading=r.root.rotation.y;actor.action={seatBlend:1-p};if(r.door)r.door.rotation.y=-Math.sin(Math.min(1,t/1.6)*Math.PI)*1.1;if(t>=1.6){actor.action=null;r.door&&(r.door.rotation.y=0);r.agent&&(r.agent.controlled=false);this.active=null;this.status('On foot');}return;}
  const extractionEnd=a.occupied?2.25:.65,entryEnd=extractionEnd+1.45,end=entryEnd+.35,enter=this.smooth((t-extractionEnd)/1.45),target=this.worldPoint(r,a.side*(this.shape(r).halfWidth+.22),0,r.root.driver.position[2]);target.y=this.world.heightAt(target.x,target.z);const backing=this.worldPoint(r,a.side*(this.shape(r).halfWidth+1.85),target.y,r.root.driver.position[2]+.25),pullProgress=this.smooth((t-.95)/1.15),pullPoint=this.B.Vector3.Lerp(target,backing,pullProgress);
  this.player.position.copyFrom(t<.65?this.lerp(a.start,target,t/.65):t<extractionEnd?pullPoint:this.B.Vector3.Lerp(a.occupied?backing:target,seat,enter));
  const face=r.root.rotation.y-a.side*Math.PI/2;this.player.heading=t<extractionEnd?face:face+((r.root.rotation.y-face+Math.PI*3)%(Math.PI*2)-Math.PI)*enter;
  this.player.speed=t<.65?1:0;actor.action={seatBlend:enter,lean:t>.6&&t<extractionEnd?.25*Math.sin(Math.min(1,(t-.6)/1.3)*Math.PI):0,reach:t>.65&&t<extractionEnd?Math.sin(Math.min(1,(t-.65)/1.35)*Math.PI):0,target:this.worldPoint(r,...[r.root.driver.position[0],r.root.driver.position[1]+1.2,r.root.driver.position[2]])};
  if(r.door)r.door.rotation.y=-1.05*this.smooth(t/.5)*(1-this.smooth((t-entryEnd)/.35));
  a.stage=t<.65?'approach':t<1.05&&a.occupied?'reach':t<extractionEnd?'pull':t<entryEnd?'enter':'seated';
  if(a.occupied&&t>.95&&!a.evicted){const victim=r.occupant,progress=this.smooth((t-.95)/1.15),pool=this.crowd.actors.extraction(victim,progress),mesh=this.victims[victim.variant];victim.occupied=false;victim.mesh.setEnabled(false);r.occupied=false;mesh.setEnabled(true);const outside=this.worldPoint(r,a.side*(this.shape(r).halfWidth+1.25),0,r.root.driver.position[2]-.5),v=this.B.Vector3.Lerp(seat,outside,progress);v.y=seat.y*(1-progress)+this.world.heightAt(outside.x,outside.z)*progress;this.crowd.actors.draw(mesh,pool,v.x,v.y,v.z,r.root.rotation.y-a.side*.8*progress,1,false);if(victim.seatOffset)mesh.position.addInPlace(victim.seatOffset.scale(1-progress));const chest=pool.nodes.Spine2||pool.nodes.Spine1;mesh.computeWorldMatrix(true);actor.action.target=this.B.Vector3.TransformCoordinates(chest.getAbsolutePosition(),this.B.Matrix.Invert(pool.world).multiply(mesh.getWorldMatrix()));if(t<extractionEnd)this.player.heading=Math.atan2(actor.action.target.x-this.player.position.x,actor.action.target.z-this.player.position.z);
   if(!a.spoke){this.speech?.play({id:r.id,variant:victim.variant},'vehicle');a.spoke=true;}
   if(progress>=1&&!a.evicted){mesh.setEnabled(false);this.releaseVictim(victim,v,r.root.rotation.y);a.evicted=true;}
   if(a.evicted)mesh.setEnabled(false);
  }
  if(t>=end){actor.action=null;if(r.door)r.door.rotation.y=0;if(r.agent){r.agent.recovery=null;r.agent.owned=true;r.agent.controlled=true;r.agent.held=false;}this.history.push({vehicle:r.id,extracted:a.occupied,duration:t});if(this.history.length>20)this.history.shift();this.active=null;this.onDrive(r);this.status('Driving '+r.name);}
 }
 releaseVictim(victim,position,heading){const e=this.evicted.find(e=>e.variant===victim.variant&&!e.visible)||this.evicted.find(e=>e.variant===victim.variant);e.position=position.clone();e.heading=heading;e.time=0;e.visible=true;e.mesh.setEnabled(true);e.idle.setEnabled(false);let goal=null,distance=Infinity;for(const route of this.crowd.routes)for(let s=0;s<route.length;s+=2){const p=this.crowd.sample(route,s),d=Math.hypot(p.x-position.x,p.z-position.z);if(d<distance){goal=p;distance=d;}}e.goal=goal||position;}
 shadowCasters(camera){return this.records.filter(r=>r.root.isEnabled()&&Math.hypot(r.root.position.x-camera.x,r.root.position.z-camera.z)<32).flatMap(r=>(r.parked?r.root.getChildMeshes():[]).concat(r.occupant?.occupied?[r.occupant.mesh]:[])).concat(this.victims.filter(m=>m.isEnabled()),this.evicted.filter(e=>e.visible).map(e=>e.idle.isEnabled()?e.idle:e.mesh));}
 snapshot(){return {action:this.active?{vehicle:this.active.record.id,stage:this.active.stage,time:+this.active.time.toFixed(2)}:null,history:this.history,evicted:this.evicted.filter(e=>e.visible).length,driverSources:this.crowd.actors.snapshot(),doors:this.records.filter(r=>r.door).map(r=>({id:r.id,triangles:r.parts.doorTriangles,wheelTriangles:r.parts.wheelTriangles})),playerModels:1};}
};
